apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: predictestate-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: predictestate.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 8000
      - path: /streamlit
        pathType: Prefix
        backend:
          service:
            name: streamlit-service
            port:
              number: 8501
