FROM apache/airflow:2.5.0
USER root
RUN apt-get update && apt-get install -y python3-dev
COPY docker/configs/airflow/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
USER airflow
