FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
# Dependencies for Selenium
RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    unzip \
    chromium \
    chromium-driver
# Dependencies for numpy/scipy
    RUN apt-get install -y \
        build-essential \
        python3-dev
RUN pip install --no-cache-dir -r requirements.txt
COPY src/ /app/src/
CMD ["uvicorn", "src.api.entrypoint:app", "--host", "0.0.0.0", "--port", "8000"]
