FROM apache/airflow:2.5.0
USER root
RUN apt-get update && apt-get install -y python3-dev
COPY docker/configs/airflow/requirements.txt .
ENV AIRFLOW_USER_HOME=/usr/local/airflow
USER airflow
RUN pip install --no-cache-dir -r requirements.txt
